version: '3.0'
services:
    coffeeshop:
        #image: coffeeshop_app:latest
        build: .
        ports:
            - "8090:8085"
        env_file:
            - config.env
        volumes:
            - ./:/app
            - ~/go/pkg/mod:/go/pkg/mod
volumes:
  go-modules: